// without login
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS'
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD'
export const EMPTY_CART = 'EMPTY_CART'


//with login
export const ADD_TO_CART_LOGIN_REQUEST = 'ADD_TO_CART_LOGIN_REQUEST'
export const ADD_TO_CART_LOGIN_SUCCESS = 'ADD_TO_CART_LOGIN_SUCCESS'
export const ADD_TO_CART_LOGIN_FAIL = 'ADD_TO_CART_LOGIN_FAIL'

export const GET_CART_REQUEST = 'GET_CART_REQUEST'
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_CART_FAIL = 'GET_CART_FAIL'

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL'

export const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST'
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS'
export const REMOVE_FROM_CART_FAIL = 'REMOVE_FROM_CART_FAIL'

export const UPDATE_CART_QUANTITY_REQUEST = 'UPDATE_CART_QUANTITY_REQUEST'
export const UPDATE_CART_QUANTITY_SUCCESS = 'UPDATE_CART_QUANTITY_SUCCESS'
export const UPDATE_CART_QUANTITY_FAIL = 'UPDATE_CART_QUANTITY_FAIL'

export const EMPTY_AUTH_CART = 'EMPTY_AUTH_CART'
export const RESET_CART_MESSAGES = 'RESET_CART_MESSAGES'


export const EMPTY_CART_DB_REQUEST = 'EMPTY_CART_DB_REQUEST'
export const EMPTY_CART_DB_SUCCESS = 'EMPTY_CART_DB_SUCCESS'
export const EMPTY_CART_DB_FAIL = 'EMPTY_CART_DB_FAIL'

