export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST'
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS'
export const PLACE_ORDER_FAIL = 'PLACE_ORDER_FAIL'


export const MY_ORDER_REQUEST = 'MY_ORDER_REQUEST'
export const MY_ORDER_SUCCESS = 'MY_ORDER_SUCCESS'
export const MY_ORDER_FAIL = 'MY_ORDER_FAIL'
export const MY_ORDER_RESET = 'MY_ORDER_RESET'


export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET'


// admin constant
export const ACTIVE_ORDER_REQUEST = 'ACTIVE_ORDER_REQUEST'
export const ACTIVE_ORDER_SUCCESS = 'ACTIVE_ORDER_SUCCESS'
export const ACTIVE_ORDER_FAIL = 'ACTIVE_ORDER_FAIL'
export const ACTIVE_ORDER_RESET = 'ACTIVE_ORDER_RESET'


export const UPDATE_DELIVERY_STATUS_REQUEST = 'UPDATE_DELIVERY_STATUS_REQUEST'
export const UPDATE_DELIVERY_STATUS_SUCCESS = 'UPDATE_DELIVERY_STATUS_SUCCESS'
export const UPDATE_DELIVERY_STATUS_FAIL = 'UPDATE_DELIVERY_STATUS_FAIL'


export const COMPLETED_ORDER_REQUEST = 'COMPLETED_ORDER_REQUEST'
export const COMPLETED_ORDER_SUCCESS = 'COMPLETED_ORDER_SUCCESS'
export const COMPLETED_ORDER_FAIL = 'COMPLETED_ORDER_FAIL'
export const COMPLETED_ORDER_RESET = 'COMPLETED_ORDER_RESET'