export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL'

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'


export const GET_PRODUCT_ACCOR_TO_CAT_REQUEST = 'GET_PRODUCT_ACCOR_TO_CAT_REQUEST'
export const GET_PRODUCT_ACCOR_TO_CAT_SUCCESS = 'GET_PRODUCT_ACCOR_TO_CAT_SUCCESS'
export const GET_PRODUCT_ACCOR_TO_CAT_FAIL = 'GET_PRODUCT_ACCOR_TO_CAT_FAIL'


export const NEW_ARRIVAL_PRODUCT_REQUEST = 'NEW_ARRIVAL_PRODUCTS_REQUEST'
export const NEW_ARRIVAL_PRODUCT_SUCCESS = 'NEW_ARRIVAL_PRODUCTS_SUCCESS'
export const NEW_ARRIVAL_PRODUCT_FAIL = 'NEW_ARRIVAL_PRODUCTS_FAIL'


export const MOST_VIEWED_PRODUCT_REQUEST = 'MOST_VIEWED_PRODUCT_REQUEST'
export const MOST_VIEWED_PRODUCT_SUCCESS = 'MOST_VIEWED_PRODUCT_SUCCESS'
export const MOST_VIEWED_PRODUCT_FAIL = 'MOST_VIEWED_PRODUCT_FAIL'


export const BEST_SELLER_PRODUCT_REQUEST = 'BEST_SELLER_PRODUCT_REQUEST'
export const BEST_SELLER_PRODUCT_SUCCESS = 'BEST_SELLER_PRODUCT_SUCCESS'
export const BEST_SELLER_PRODUCT_FAIL = 'BEST_SELLER_PRODUCT_FAIL'


export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL'


export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'


export const REVIEW_PRODUCT_REQUEST = 'REVIEW_PRODUCT_REQUEST'
export const REVIEW_PRODUCT_SUCCESS = 'REVIEW_PRODUCT_SUCCESS'
export const REVIEW_PRODUCT_FAIL = 'REVIEW_PRODUCT_FAIL'
export const REVIEW_PRODUCT_RESET = 'REVIEW_PRODUCT_RESET'

